[window]
opacity = 0.97
padding.x = 200
padding.y = 90
startup_mode = "Maximized"
[scrolling]
history = 10_000
[font]
normal = { style = "bold", family = "JetBrainsMono Nerd Font" }
# bold = { style = "Bold", family = "JetBrainsMono Nerd Font" }
# bold_italic = { style = "Bold Italic", family = "JetBrainsMono Nerd Font" }
# italic = { style = "Italic", family = "JetBrainsMono" }
size = 15.0
[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

# [shell]
# program = "/bin/zsh"
# args = ["-c", "tmux"]
